title: Editor and Graphics Programmer for the RSX Engine
subtitle: Professional game engine development role
start_date: '2020-08-01'
end_date: '2021-12-31'
tech: C++, csharp, 3D Programming, Game Engine Development
image_layout: featured
github_url:
live_url: https://rsxengine.com/

description: |
  I worked as a contractor for Abstract to work on their game engine RSX. As I joined the team the engine was already fully functional but needed a lot of polish and bug fixing.
  
  I contributed in a few areas, mainly the macOS platform layer, the rendering of Gizmo in the editor, scene picking and manupilation tools and editor functionalities such as shortcuts, Undo/Reddo, etc...
  
  On the macOS layer I made sure the windowing system was working robustly with multiple windows in multiple monitors, and that events were properly propagated to the engine's UI system.
  
  I also wrote and maintained some C# code on the UI scripting layer that was built in the engine.
  The engine since switched to Typescrit to be able to run the editor on the web.