title: Editor and Graphics Programmer for the RSX Engine
subtitle: Professional game engine development role
start_date: '2020-08-01'
end_date: '2021-12-31'
tech: C++, OpenGL, DirectX, Game Engine Development
image_layout: featured
github_url:
live_url: https://rsxengine.com/

description: |
  Worked as Editor and Graphics Programmer for the RSX Engine, a professional game engine development project.
  During this role, I focused on developing and maintaining the engine's editor tools and graphics rendering systems.
  
  Key responsibilities included:
  - Developing and maintaining the engine's editor interface
  - Implementing graphics rendering features using OpenGL and DirectX
  - Optimizing rendering pipelines for better performance
  - Collaborating with the development team on engine architecture
  - Debugging and fixing graphics-related issues
  
  This position provided valuable experience in professional game engine development and graphics programming.
