title: Hakomi Practice Timer
subtitle: A solution to a quite specific real world problem
description: A timer to make timing hakomi practice sessions easier.
start_date: '2025-08-16'
end_date: '2025-08-24'
tech: React, Vite, Pico
