title: Game Development in Rust - Study around SnakeBird
description: A few projects of game development exploring gameplay inspired by the game SnakeBird
start_date: '2025-08-26'
end_date: '2023-12-29'
tech:
  - name: rust
    icon: /portfolio/icons/rust.svg
    iconType: svg
  - name: bevy
    icon: null
    iconType: null
images: []
